### ISSUE TITLE
Activity shares icon with river crossing activity

### ISSUE THREAD

**Issue by chimosky** [marsian83/nim-game-activity#2]
This activity shares the same icon with river crossing, I'm guessing you forgot to change it.

@marsian83 bringing your attention to this.

**Comment by marsian83** [comment]
I am making an icon
I still have not been able to fetch the colors from user profile colors to show in activity icons like many other activities do
Can you help me with that?

**Comment by marsian83** [comment]
I added the icon, still need help with grabbing colors from sugar profile though

**Comment by chimosky** [comment]
> I am making an icon I still have not been able to fetch the colors from user profile colors to show in activity icons like many other activities do Can you help me with that?

Looking at the activity icon, seems you didn't use inkscape and we typically advice using inkscape, you're missing two key entities `stroke_color` and `fill_color`, see [making icons](https://wiki.sugarlabs.org/go/Development_Team/Almanac/Making_Icons).

**Comment by marsian83** [comment]
I will recreate using inkscape, 
I have added "help" and "show theory" besides I will be pushing the "settings" page within an hour or so

**Comment by chimosky** [comment]
Tested 52dda7a, the font used in the theory isn't good as it's really small and would be difficult to see.

This is what it looks like with some texts bigger than the other and I don't see the reasoning behind that, if they were made bold I'd understand.
![Screenshot from 2024-08-15 17-38-34](https://github.com/user-attachments/assets/e5587ad1-2f38-43da-9f6d-f3b78c275dea)

**Comment by marsian83** [comment]
Should I adjust the images in photoshop?

**Comment by chimosky** [comment]
> Should I adjust the images in photoshop?

You should adjust using what you used before.

**Comment by marsian83** [comment]
![image](https://github.com/user-attachments/assets/6adb0298-0158-4f96-9f5a-5dcad7783274)
managed to make it look liek this

**Comment by chimosky** [comment]
Still doesn't look great, the text doesn't have to overflow to the end of the canvas and there's also no need to make some text bigger and bold.

**Comment by marsian83** [comment]
I have updated this and made a more summarized version. Can you take a look

**Comment by marsian83** [comment]
I have also fixed multiple flake8 issues

**Comment by chimosky** [comment]
Could you transfer ownership of this repo? It'll be easier to review your changes and agree on those changes, and make corrections if necessary.

**Comment by marsian83** [comment]
Yes, That works
but I reckon you will have to delete this fork, I can not initiate transfer as this already exists
[Nim Game](https://github.com/sugarlabs/nim-game-activity)

Please do the same for the `river-crossing-activity` as well
[River-crossing-activity](https://github.com/sugarlabs/river-crossing-activity)

**Comment by chimosky** [comment]
Transfer the ownership to me, then I'll transfer it to Sugar Labs.

**Comment by chimosky** [comment]
Tested your changes, your use of the plus sign in a circle can be confusing, also aim to simplify the language to something a kid can understand.

The game freezes on the help menu, the icon isn't filled properly, the edges are filled but not the icon itself.

This was in the logs;
```python3
Traceback (most recent call last):
  File "/home/ibiam/Activities/nim-game-activity/main.py", line 82, in run
    self.update_function()
  File "/home/ibiam/Activities/nim-game-activity/views/theory.py", line 64, in update
    next_btn.update()
  File "/home/ibiam/Activities/nim-game-activity/components/button.py", line 52, in update
    Clickable.update(self)
  File "/home/ibiam/Activities/nim-game-activity/components/common.py", line 36, in update
    self.on_click()
  File "/home/ibiam/Activities/nim-game-activity/views/theory.py", line 50, in <lambda>
    next_btn.on_click = lambda: set_theory_page(
                                ^^^^^^^^^^^^^^^^
  File "/home/ibiam/Activities/nim-game-activity/views/theory.py", line 30, in set_theory_page
    theory_page = config.images["label"][f"theory_{page_no}"]
                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'theory_3'
```

**Comment by marsian83** [comment]
Completed this issue

**Comment by chimosky** [comment]
Haven't tested yet to know, will test when I can.
